system:
    debug: 0
    timezone: 'UTC'
    secret: 2ffcaf26cb281852bf231f5ff85b476a
    error_reporting: 0
session:
    handler: native
    expire_time: 15
cache:
    enabled: 0
    storage: file
    handler: serialize
    dir: cache
    time: 15
language:
    debug: 0
    locale: en-GB
    default: en-GB
    format: ini
    path: resources/languages
database:
    mysql_strict_mode: false
